interface Language {
  code: string;
  name: string;
  flag: string;
  region?: string;
}

// export const languages: Language[] = [
//   { code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
//   { code: 'sq', name: 'Albanian', flag: '🇦🇱' },
//   { code: 'am', name: 'Amharic', flag: '🇪🇹' },
//   { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
//   { code: 'hy', name: 'Armenian', flag: '🇦🇲' },
//   { code: 'as', name: 'Assamese', flag: '🇮🇳' },
//   { code: 'ast', name: 'Asturian', flag: '🏴󠁥󠁳󠁡󠁳󠁿' },
//   { code: 'az', name: 'Azerbaijani', flag: '🇦🇿' },
//   { code: 'ba', name: 'Bashkir', flag: '🇷🇺' },
//   { code: 'eu', name: 'Basque', flag: '🏴󠁥󠁳󠁰󠁶󠁿' },
//   { code: 'be', name: 'Belarusian', flag: '🇧🇾' },
//   { code: 'bn', name: 'Bengali', flag: '🇧🇩' },
//   { code: 'bs', name: 'Bosnian', flag: '🇧🇦' },
//   { code: 'br', name: 'Breton', flag: '🏴󠁦󠁲󠁢󠁲󠁥󠁿' },
//   { code: 'bg', name: 'Bulgarian', flag: '🇧🇬' },
//   { code: 'my', name: 'Burmese', flag: '🇲🇲' },
//   { code: 'ca', name: 'Catalan', flag: '🏴󠁥󠁳󠁣󠁴󠁿' },
//   { code: 'ceb', name: 'Cebuano', flag: '🇵🇭' },
//   { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
//   { code: 'zh-TW', name: 'Chinese', flag: '🇹🇼', region: 'Traditional' },
//   { code: 'hr', name: 'Croatian', flag: '🇭🇷' },
//   { code: 'cs', name: 'Czech', flag: '🇨🇿' },
//   { code: 'da', name: 'Danish', flag: '🇩🇰' },
//   { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
//   { code: 'nl-BE', name: 'Dutch', flag: '🇧🇪', region: 'Belgium' },
//   { code: 'en', name: 'English', flag: '🌐' },
//   { code: 'en-AU', name: 'English', flag: '🇦🇺', region: 'Australia' },
//   { code: 'en-GB', name: 'English', flag: '🇬🇧', region: 'UK' },
//   { code: 'en-IN', name: 'English', flag: '🇮🇳', region: 'India' },
//   { code: 'en-NZ', name: 'English', flag: '🇳🇿', region: 'New Zealand' },
//   { code: 'en-US', name: 'English', flag: '🇺🇸', region: 'US' },
//   { code: 'et', name: 'Estonian', flag: '🇪🇪' },
//   { code: 'fo', name: 'Faroese', flag: '🇫🇴' },
//   { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
//   { code: 'fr', name: 'French', flag: '🇫🇷' },
//   { code: 'fr-CA', name: 'French', flag: '🇨🇦', region: 'Canada' },
//   { code: 'ff', name: 'Fula', flag: '🇸🇳' },
//   { code: 'gl', name: 'Galician', flag: '🏴󠁥󠁳󠁧󠁡󠁿' },
//   { code: 'ka', name: 'Georgian', flag: '🇬🇪' },
//   { code: 'de', name: 'German', flag: '🇩🇪' },
//   { code: 'de-CH', name: 'German', flag: '🇨🇭', region: 'Switzerland' },
//   { code: 'el', name: 'Greek', flag: '🇬🇷' },
//   { code: 'gu', name: 'Gujarati', flag: '🇮🇳' },
//   { code: 'ht', name: 'Haitian Creole', flag: '🇭🇹' },
//   { code: 'ha', name: 'Hausa', flag: '🇳🇬' },
//   { code: 'haw', name: 'Hawaiian', flag: '🌺' },
//   { code: 'he', name: 'Hebrew', flag: '🇮🇱' },
//   { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
//   { code: 'hu', name: 'Hungarian', flag: '🇭🇺' },
//   { code: 'is', name: 'Icelandic', flag: '🇮🇸' },
//   { code: 'ig', name: 'Igbo', flag: '🇳🇬' },
//   { code: 'ilo', name: 'Ilocano', flag: '🇵🇭' },
//   { code: 'id', name: 'Indonesian', flag: '🇮🇩' },
//   { code: 'ga', name: 'Irish', flag: '🇮🇪' },
//   { code: 'it', name: 'Italian', flag: '🇮🇹' },
//   { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
//   { code: 'jv', name: 'Javanese', flag: '🇮🇩' },
//   { code: 'kn', name: 'Kannada', flag: '🇮🇳' },
//   { code: 'kk', name: 'Kazakh', flag: '🇰🇿' },
//   { code: 'km', name: 'Khmer', flag: '🇰🇭' },
//   { code: 'ko', name: 'Korean', flag: '🇰🇷' },
//   { code: 'la', name: 'Latin', flag: '🏛️' },
//   { code: 'lv', name: 'Latvian', flag: '🇱🇻' },
//   { code: 'ln', name: 'Lingala', flag: '🇨🇩' },
//   { code: 'lt', name: 'Lithuanian', flag: '🇱🇹' },
//   { code: 'lg', name: 'Luganda', flag: '🇺🇬' },
//   { code: 'lb', name: 'Luxembourgish', flag: '🇱🇺' },
//   { code: 'mk', name: 'Macedonian', flag: '🇲🇰' },
//   { code: 'mg', name: 'Malagasy', flag: '🇲🇬' },
//   { code: 'ms', name: 'Malay', flag: '🇲🇾' },
//   { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
//   { code: 'mt', name: 'Maltese', flag: '🇲🇹' },
//   { code: 'mi', name: 'Maori', flag: '🇳🇿' },
//   { code: 'mr', name: 'Marathi', flag: '🇮🇳' },
//   { code: 'mo', name: 'Moldovan', flag: '🇲🇩' },
//   { code: 'mn', name: 'Mongolian', flag: '🇲🇳' },
//   { code: 'multi', name: 'Multilingual', flag: '🌐' },
//   { code: 'ne', name: 'Nepali', flag: '🇳🇵' },
//   { code: 'no', name: 'Norwegian', flag: '🇳🇴' },
//   { code: 'nn', name: 'Norwegian Nynorsk', flag: '🇳🇴' },
//   { code: 'oc', name: 'Occitan', flag: '🇫🇷' },
//   { code: 'or', name: 'Odia', flag: '🇮🇳' },
//   { code: 'ps', name: 'Pashto', flag: '🇦🇫' },
//   { code: 'fa', name: 'Persian', flag: '🇮🇷' },
//   { code: 'pl', name: 'Polish', flag: '🇵🇱' },
//   { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
//   { code: 'pt-BR', name: 'Portuguese', flag: '🇧🇷', region: 'Brazil' },
//   { code: 'pa', name: 'Punjabi', flag: '🇮🇳' },
//   { code: 'ro', name: 'Romanian', flag: '🇷🇴' },
//   { code: 'ru', name: 'Russian', flag: '🇷🇺' },
//   { code: 'sa', name: 'Sanskrit', flag: '🇮🇳' },
//   { code: 'gd', name: 'Scottish Gaelic', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
//   { code: 'sr', name: 'Serbian', flag: '🇷🇸' },
//   { code: 'sn', name: 'Shona', flag: '🇿🇼' },
//   { code: 'sd', name: 'Sindhi', flag: '🇵🇰' },
//   { code: 'si', name: 'Sinhala', flag: '🇱🇰' },
//   { code: 'sk', name: 'Slovak', flag: '🇸🇰' },
//   { code: 'sl', name: 'Slovenian', flag: '🇸🇮' },
//   { code: 'so', name: 'Somali', flag: '🇸🇴' },
//   { code: 'es', name: 'Spanish', flag: '🇪🇸' },
//   { code: 'es-419', name: 'Spanish', flag: '🇲🇽', region: 'Latin America' },
//   { code: 'su', name: 'Sundanese', flag: '🇮🇩' },
//   { code: 'ss', name: 'Swati', flag: '🇸🇿' },
//   { code: 'sw', name: 'Swahili', flag: '🇹🇿' },
//   { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
//   { code: 'tg', name: 'Tajik', flag: '🇹🇯' },
//   { code: 'tl', name: 'Tagalog', flag: '🇵🇭' },
//   { code: 'ta', name: 'Tamil', flag: '🇮🇳' },
//   { code: 'tt', name: 'Tatar', flag: '🇷🇺' },
//   { code: 'te', name: 'Telugu', flag: '🇮🇳' },
//   { code: 'th', name: 'Thai', flag: '🇹🇭' },
//   { code: 'th-TH', name: 'Thai', flag: '🇹🇭', region: 'Thailand' },
//   { code: 'bo', name: 'Tibetan', flag: '🏳️' },
//   { code: 'tn', name: 'Tswana', flag: '🇧🇼' },
//   { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
//   { code: 'tk', name: 'Turkmen', flag: '🇹🇲' },
//   { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
//   { code: 'ur', name: 'Urdu', flag: '🇵🇰' },
//   { code: 'uz', name: 'Uzbek', flag: '🇺🇿' },
//   { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
//   { code: 'cy', name: 'Welsh', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
//   { code: 'wo', name: 'Wolof', flag: '🇸🇳' },
//   { code: 'xh', name: 'Xhosa', flag: '🇿🇦' },
//   { code: 'yi', name: 'Yiddish', flag: '🕎' },
//   { code: 'yo', name: 'Yoruba', flag: '🇳🇬' },
//   { code: 'zu', name: 'Zulu', flag: '🇿🇦' },
// ];

export const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🌐' },
  { code: 'en-AU', name: 'English', flag: '🇦🇺', region: 'Australia' },
  { code: 'en-GB', name: 'English', flag: '🇬🇧', region: 'UK' },
];
